# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: gncs

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - name: install npm dependencies
    - run: npm ci
    # - run: npm run build --if-present
    # - name: test web app
    - run: npm test

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: gncs/web-app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
    #   env:
    #       GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.STAGE_GNCS_HOST }}
        username: ${{ secrets.STAGE_GNCS_DEPLOY }}
        password: ${{ secrets.STAGE_NGCS_DEPLOY_PASSWORD }}
        # port: ${{ secrets.STAGE_PORT }} # default port 22
        script: |
          docker stop gncs
          docker container rm gncs
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull gncs/web-app:develop
          docker run --name gncs -dit -p 8080:80 gncs/web-app:develop
